"""
Gemini Agent for WAF Rule Refinement and Comparison.

This agent acts as a second opinion to refine, deduplicate,
and validate WAF rules generated by the primary LLM.

Pipeline position:
    [1] LLM + RAG -> Generate Rules
    [2] Syntax Validator -> Check syntax
    [3] Gemini Agent -> Refine & Compare (this module)
    [4] Output final rules
"""

import os
import json
from typing import Optional
from dataclasses import dataclass, field

try:
    from google import genai
except ImportError:
    genai = None


@dataclass
class RefinementResult:
    """Result of rule refinement by Gemini agent."""
    success: bool
    refined_rules: list[dict] = field(default_factory=list)
    removed_duplicates: int = 0
    improvements_made: list[str] = field(default_factory=list)
    comparison_notes: str = ""
    error_message: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "refined_rules": self.refined_rules,
            "removed_duplicates": self.removed_duplicates,
            "improvements_made": self.improvements_made,
            "comparison_notes": self.comparison_notes,
            "error_message": self.error_message,
        }


class GeminiRuleAgent:
    """
    Gemini-based agent for WAF rule refinement.

    Responsibilities:
    1. Compare new rules with existing rules (avoid duplicates)
    2. Refine rule patterns for better coverage
    3. Optimize rule performance
    4. Validate rule logic and effectiveness

    Usage:
        agent = GeminiRuleAgent()
        result = agent.refine_rules(
            new_rules=[...],
            existing_rules=[...],
            bypassed_payloads=[...]
        )
    """

    SYSTEM_PROMPT = """You are an expert WAF rule engineer and security analyst. Your task is to:

1. **Review and Refine WAF Rules**: Improve the effectiveness and performance of generated rules
2. **Deduplicate**: Identify and merge rules that have overlapping coverage
3. **Optimize Patterns**: Improve regex patterns for better performance and accuracy
4. **Validate Coverage**: Ensure rules actually block the bypassed payloads
5. **Compare with Existing**: Avoid creating rules that duplicate existing ones

You must output valid JSON only. Be concise and technical."""

    REFINEMENT_PROMPT_TEMPLATE = """## Task: Refine and Validate WAF Rules

### Bypassed Payloads (must be blocked):
{bypassed_payloads}

### Newly Generated Rules:
{new_rules}

### Existing Rules (avoid duplicates):
{existing_rules}

### Instructions:
1. **Validate Coverage**: Check each new rule against bypassed payloads
2. **Remove Duplicates**: If a new rule overlaps with existing rules, merge or remove it
3. **Optimize Patterns**: Improve regex for performance (avoid catastrophic backtracking)
4. **Add Transformations**: Ensure proper normalization (urlDecode, lowercase, etc.)
5. **Fix Issues**: Correct any syntax or logic errors

### Output Format (JSON):
{{
    "refined_rules": [
        {{
            "rule": "SecRule ... (the complete rule)",
            "instructions": "deployment instructions",
            "changes_made": "what was improved or why kept as-is"
        }}
    ],
    "removed_rules": [
        {{
            "original_rule": "the rule that was removed",
            "reason": "why it was removed (duplicate, ineffective, etc.)"
        }}
    ],
    "comparison_notes": "summary of comparison with existing rules",
    "coverage_analysis": "whether all bypassed payloads are now covered"
}}

Respond ONLY with valid JSON, no markdown code blocks."""

    def __init__(self, api_key: Optional[str] = None, model: str = "gemini-2.5-flash"):
        """
        Initialize Gemini agent.

        Args:
            api_key: Google AI API key (or set GOOGLE_API_KEY env var)
            model: Gemini model to use (default: gemini-2.5-flash for rule comparison)
        """
        self.model_name = model
        self.model = None
        self.available = False

        if genai is None:
            print("Warning: google-generativeai not installed. Run: pip install google-generativeai")
            return

        # Get API key
        api_key = api_key or os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")

        if not api_key:
            print("Warning: No Google API key found. Set GOOGLE_API_KEY or GEMINI_API_KEY env var.")
            return

        try:
            self.client = genai.Client(api_key=api_key)
            self.available = True
        except Exception as e:
            print(f"Warning: Failed to initialize Gemini: {e}")

    def refine_rules(
        self,
        new_rules: list[dict],
        bypassed_payloads: list[str],
        existing_rules: Optional[list[dict]] = None,
        waf_type: str = "ModSecurity"
    ) -> RefinementResult:
        """
        Refine generated rules using Gemini.

        Args:
            new_rules: List of newly generated rules [{"rule": "...", "instructions": "..."}]
            bypassed_payloads: List of payloads that bypassed the WAF
            existing_rules: Optional list of existing rules to compare against
            waf_type: Type of WAF (for context)

        Returns:
            RefinementResult with refined rules and metadata
        """
        if not self.available:
            # Return original rules if Gemini not available
            return RefinementResult(
                success=True,
                refined_rules=new_rules,
                comparison_notes="Gemini agent not available - returning original rules"
            )

        if not new_rules:
            return RefinementResult(
                success=False,
                error_message="No rules provided for refinement"
            )

        max_attempts = 10
        for i in range(max_attempts):
            try:
                # Format inputs
                payloads_str = json.dumps(bypassed_payloads[:10], indent=2)  # Limit for token efficiency
                new_rules_str = json.dumps(new_rules, indent=2)
                existing_rules_str = json.dumps(existing_rules or [], indent=2)

                # Build prompt
                prompt = self.REFINEMENT_PROMPT_TEMPLATE.format(
                    bypassed_payloads=payloads_str,
                    new_rules=new_rules_str,
                    existing_rules=existing_rules_str if existing_rules else "(none)"
                )

                # Call Gemini
                response = self.client.models.generate_content(
                    model=self.model_name,
                    contents=self.SYSTEM_PROMPT + "\n\n" + prompt,
                )

                # Parse response
                response_text = response.text.strip()

                # Clean up response (remove markdown code blocks if present)
                if response_text.startswith("```"):
                    lines = response_text.split("\n")
                    response_text = "\n".join(lines[1:-1])

                result_json = json.loads(response_text)

                # Build result
                refined_rules = result_json.get("refined_rules", new_rules)
                removed_rules = result_json.get("removed_rules", [])

                improvements = []
                for rule in refined_rules:
                    if rule.get("changes_made"):
                        improvements.append(rule["changes_made"])

                return RefinementResult(
                    success=True,
                    refined_rules=refined_rules,
                    removed_duplicates=len(removed_rules),
                    improvements_made=improvements,
                    comparison_notes=result_json.get("comparison_notes", "")
                )

            except json.JSONDecodeError as e:
                return RefinementResult(
                    success=False,
                    refined_rules=new_rules,  # Return original on error
                    error_message=f"Failed to parse Gemini response: {e}"
                )
            except Exception as e:
                if "503 UNAVAILABLE" in str(e):
                    print(f"Gemini service unavailable (attempt {i+1}/{max_attempts}), retrying...")
                    continue
                return RefinementResult(
                    success=False,
                    refined_rules=new_rules,
                    error_message=f"Gemini refinement failed: {e}"
                )

    def compare_rules(
        self,
        rule1: str,
        rule2: str
    ) -> dict:
        """
        Compare two rules for overlap/similarity.

        Args:
            rule1: First rule string
            rule2: Second rule string

        Returns:
            Dict with comparison analysis
        """
        if not self.available:
            return {"error": "Gemini not available", "similar": False}

        try:
            prompt = f"""Compare these two WAF rules and determine if they have overlapping coverage:

Rule 1: {rule1}

Rule 2: {rule2}

Output JSON:
{{
    "similar": true/false,
    "overlap_percentage": 0-100,
    "recommendation": "keep_both" | "merge" | "keep_rule1" | "keep_rule2",
    "reason": "explanation"
}}"""

            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
            )
            return json.loads(response.text.strip())

        except Exception as e:
            return {"error": str(e), "similar": False}

    def validate_rule_coverage(
        self,
        rule: str,
        payloads: list[str]
    ) -> dict:
        """
        Validate if a rule would block given payloads.

        Args:
            rule: WAF rule string
            payloads: List of payloads to test

        Returns:
            Dict with coverage analysis
        """
        if not self.available:
            return {"error": "Gemini not available", "coverage": "unknown"}

        try:
            prompt = f"""Analyze if this WAF rule would block these payloads:

Rule: {rule}

Payloads:
{json.dumps(payloads[:5], indent=2)}

Output JSON:
{{
    "would_block": ["payload1", "payload2"],
    "would_miss": ["payload3"],
    "coverage_percentage": 0-100,
    "issues": ["any issues with the rule"]
}}"""

            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
            )
            return json.loads(response.text.strip())

        except Exception as e:
            return {"error": str(e), "coverage": "unknown"}


def get_gemini_agent(
    api_key: Optional[str] = None,
    model: str = "gemini-2.5-flash"
) -> GeminiRuleAgent:
    """
    Get Gemini agent instance.

    Args:
        api_key: Optional API key
        model: Model to use

    Returns:
        GeminiRuleAgent instance
    """
    return GeminiRuleAgent(api_key=api_key, model=model)
