"""
Rule refinement agent for WAF rule refinement and comparison.

This agent acts as a second opinion to refine, deduplicate,
and validate WAF rules generated by the primary LLM.

Pipeline position:
    [1] LLM + RAG -> Generate Rules
    [2] Syntax Validator -> Check syntax
    [3] Refine Rule Agent -> Refine & Compare (this module)
    [4] Output final rules
"""

import json
from dataclasses import dataclass, field
from typing import Optional

try:
    from gui.backend.services_external.llm import claude_completion
except ImportError:
    from ..gui.backend.services_external.llm import claude_completion


@dataclass
class RefinementResult:
    """Result of rule refinement."""
    success: bool
    refined_rules: list[dict] = field(default_factory=list)
    removed_duplicates: int = 0
    improvements_made: list[str] = field(default_factory=list)
    comparison_notes: str = ""
    error_message: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "refined_rules": self.refined_rules,
            "removed_duplicates": self.removed_duplicates,
            "improvements_made": self.improvements_made,
            "comparison_notes": self.comparison_notes,
            "error_message": self.error_message,
        }


class RefineRuleAgent:
    """
    Claude-based agent for WAF rule refinement.

    Responsibilities:
    1. Compare new rules with existing rules
    2. Refine rule patterns for better coverage
    3. Optimize rule performance
    4. Validate rule logic and effectiveness
    """

    SYSTEM_PROMPT = """You are an expert WAF rule engineer and security analyst. Your task is to:

1. Review and refine WAF rules for effectiveness and performance.
2. Deduplicate rules that have overlapping coverage.
3. Optimize patterns to avoid over-broad or slow matching.
4. Validate that the rules cover the bypassed payloads.
5. Avoid duplicating existing rules.

Return valid JSON only. No markdown. Be concise and technical."""

    REFINEMENT_PROMPT_TEMPLATE = """## Task: Refine and Validate WAF Rules

### WAF Type:
{waf_type}

### Bypassed Payloads (must be blocked):
{bypassed_payloads}

### Newly Generated Rules:
{new_rules}

### Existing Rules (avoid duplicates):
{existing_rules}

### Instructions:
1. Validate rule coverage against the payloads.
2. Remove or merge duplicates.
3. Optimize patterns for performance and precision.
4. Ensure the rules remain in the correct WAF syntax.
5. Return only deployable rules.

### Output Format (JSON):
{{
    "refined_rules": [
        {{
            "rule": "complete rule text",
            "instructions": "deployment instructions",
            "changes_made": "what changed or why it was kept"
        }}
    ],
    "removed_rules": [
        {{
            "original_rule": "removed rule text",
            "reason": "duplicate, ineffective, or superseded"
        }}
    ],
    "comparison_notes": "short summary",
    "coverage_analysis": "short coverage statement"
}}
"""

    COMPARE_PROMPT_TEMPLATE = """Compare these two WAF rules and determine whether they overlap in coverage.

Rule 1:
{rule1}

Rule 2:
{rule2}

Return JSON:
{{
    "similar": true,
    "overlap_percentage": 0,
    "recommendation": "keep_both",
    "reason": "brief explanation"
}}
"""

    COVERAGE_PROMPT_TEMPLATE = """Analyze whether this WAF rule would block the following payloads.

Rule:
{rule}

Payloads:
{payloads}

Return JSON:
{{
    "would_block": [],
    "would_miss": [],
    "coverage_percentage": 0,
    "issues": []
}}
"""

    def __init__(self, model: str = "claude-sonnet-4-6"):
        self.model_name = model
        self.available = True

    def _call_claude_json(self, user_prompt: str, response_name: str, response_schema: dict) -> dict:
        response = claude_completion(
            messages=[
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            model=self.model_name,
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": response_name,
                    "schema": response_schema,
                },
            },
        )

        content = response.get("choices", [{}])[0].get("message", {}).get("content", "")
        if not content:
            raise ValueError(f"Claude returned empty content: {response}")

        return json.loads(content)

    def refine_rules(
        self,
        new_rules: list[dict],
        bypassed_payloads: list[str],
        existing_rules: Optional[list[dict]] = None,
        waf_type: str = "ModSecurity",
    ) -> RefinementResult:
        if not new_rules:
            return RefinementResult(success=False, error_message="No rules provided for refinement")

        schema = {
            "type": "object",
            "properties": {
                "refined_rules": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "rule": {"type": "string"},
                            "instructions": {"type": "string"},
                            "changes_made": {"type": "string"},
                        },
                        "required": ["rule", "instructions", "changes_made"],
                    },
                },
                "removed_rules": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "original_rule": {"type": "string"},
                            "reason": {"type": "string"},
                        },
                        "required": ["original_rule", "reason"],
                    },
                },
                "comparison_notes": {"type": "string"},
                "coverage_analysis": {"type": "string"},
            },
            "required": ["refined_rules", "removed_rules", "comparison_notes", "coverage_analysis"],
        }

        prompt = self.REFINEMENT_PROMPT_TEMPLATE.format(
            waf_type=waf_type,
            bypassed_payloads=json.dumps(bypassed_payloads[:10], indent=2),
            new_rules=json.dumps(new_rules, indent=2),
            existing_rules=json.dumps(existing_rules or [], indent=2),
        )

        max_attempts = 5
        for attempt in range(max_attempts):
            try:
                result_json = self._call_claude_json(prompt, "RuleRefinement", schema)
                refined_rules = result_json.get("refined_rules", new_rules)
                removed_rules = result_json.get("removed_rules", [])
                improvements = [
                    rule.get("changes_made", "")
                    for rule in refined_rules
                    if rule.get("changes_made")
                ]

                return RefinementResult(
                    success=True,
                    refined_rules=refined_rules,
                    removed_duplicates=len(removed_rules),
                    improvements_made=improvements,
                    comparison_notes=result_json.get("comparison_notes", ""),
                )
            except json.JSONDecodeError as exc:
                return RefinementResult(
                    success=False,
                    refined_rules=new_rules,
                    error_message=f"Failed to parse Claude response: {exc}",
                )
            except Exception as exc:
                if "503" in str(exc) and attempt < max_attempts - 1:
                    continue
                return RefinementResult(
                    success=False,
                    refined_rules=new_rules,
                    error_message=f"Rule refinement failed: {exc}",
                )

        return RefinementResult(
            success=False,
            refined_rules=new_rules,
            error_message="Rule refinement failed after retries",
        )

    def compare_rules(self, rule1: str, rule2: str) -> dict:
        schema = {
            "type": "object",
            "properties": {
                "similar": {"type": "boolean"},
                "overlap_percentage": {"type": "number"},
                "recommendation": {"type": "string"},
                "reason": {"type": "string"},
            },
            "required": ["similar", "overlap_percentage", "recommendation", "reason"],
        }

        try:
            return self._call_claude_json(
                self.COMPARE_PROMPT_TEMPLATE.format(rule1=rule1, rule2=rule2),
                "RuleComparison",
                schema,
            )
        except Exception as exc:
            return {"error": str(exc), "similar": False}

    def validate_rule_coverage(self, rule: str, payloads: list[str]) -> dict:
        schema = {
            "type": "object",
            "properties": {
                "would_block": {"type": "array", "items": {"type": "string"}},
                "would_miss": {"type": "array", "items": {"type": "string"}},
                "coverage_percentage": {"type": "number"},
                "issues": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["would_block", "would_miss", "coverage_percentage", "issues"],
        }

        try:
            return self._call_claude_json(
                self.COVERAGE_PROMPT_TEMPLATE.format(
                    rule=rule,
                    payloads=json.dumps(payloads[:5], indent=2),
                ),
                "RuleCoverage",
                schema,
            )
        except Exception as exc:
            return {"error": str(exc), "coverage": "unknown"}


def get_refine_rule_agent(model: str = "claude-sonnet-4-6") -> RefineRuleAgent:
    """Get rule refinement agent instance."""
    return RefineRuleAgent(model=model)